import lldb

def __lldb_init_module(debugger, dict):
    lldb.formatters.cpp.libcxx_map_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_atomic_formatter.__lldb_init_module(debugger, dict)
    #lldb.formatters.cpp.libcxx_chrono_formatter.__lldb_init_module(debugger, dict)
    #lldb.formatters.cpp.libcxx_function_formatter.__lldb_init_module(debugger, dict)
    #lldb.formatters.cpp.libcxx_ordering_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_proxy_array_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_queue_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_ranges_ref_view_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_shared_ptr_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_slice_array_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_span_formatter.__lldb_init_module(debugger, dict)
    #lldb.formatters.cpp.libcxx_string_formatter.__lldb_init_module(debugger, dict)
    #lldb.formatters.cpp.libcxx_string_view_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_tuple_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_unique_ptr_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_unordered_map_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_valarray_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_variant_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_vector_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_vector_iterator_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_deque_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_optional_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_bitset_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_forward_list_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_list_formatter.__lldb_init_module(debugger, dict)
    lldb.formatters.cpp.libcxx_coroutine_handle_formatter.__lldb_init_module(debugger, dict)

    debugger.HandleCommand(f'type category enable cplusplus-py')
